# Generated by Django 3.2.4 on 2021-06-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_student_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='branches/'),
        ),
    ]
