# Generated by Django 3.2.4 on 2021-06-16 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_branch_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='student',
            name='photo',
        ),
    ]
